- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    connectedServiceName: 'ToyWebsites'
    location: 'westus3'
    resourceGroupName: 'ToyWebsites'
    csmFile: 'ToyWebsites'/main.bicep
    overrideParameters: >
        -parameterName parameterValue